
# Problem: 202. Happy Number
#
# Description:
# A happy number is a number where we repeatedly replace the number
# with the sum of the squares of its digits.
# If the process finally reaches 1, the number is happy.
# If the process starts repeating the same number, it means there is a loop,
# so the number is not happy.
#
# Approach:
# 1. Use a set to store all numbers we have already seen.
# 2. While n is not equal to 1:
#    - If n is already in the set, return False (loop detected).
#    - Add n to the set.
#    - Find the sum of the squares of its digits.
#    - Update n with this new sum.
# 3. If n becomes 1, return True.
#
# Logic:
# - If a number reaches 1 -> Happy Number
# - If a number repeats -> Infinite loop -> Not Happy Number
# - We use a set to remember previously visited numbers.
#
# Example:
# 19 -> 82 -> 68 -> 100 -> 1
# So, 19 is a happy number.
#
# Why this works:
# - Every new number is generated by summing the square of digits.
# - There are only two possibilities:
#   1. It reaches 1
#   2. It enters a cycle
# - The set helps us detect the cycle quickly.
#
# Memory Trick (for future revision):
# "1 means Happy, Repeat means Not Happy"
#
# Time Complexity: O(log n) per transformation
# Space Complexity: O(k), where k is the number of visited values

class Solution:
    def isHappy(self, n: int) -> bool:
        seen = set()

        while n != 1:
            if n in seen:
                return False

            seen.add(n)

            total = 0
            while n > 0:
                digit = n % 10
                total += digit * digit
                n //= 10

            n = total

        return True